name: app_quanly_giaidau
description: "Ứng dụng Quản lý Giải đấu Thể thao"
publish_to: 'none'
version: 1.0.15+18

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/icon.png"

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.3.1

  # Navigation
  go_router: ^17.2.3

  # UI
  google_fonts: ^8.1.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  flutter_svg: ^2.3.0
  flutter_widget_from_html: ^0.15.2

  # Import/Export
  excel: ^4.0.6
  csv: ^8.0.0
  file_picker: ^12.0.0-beta.5
  pdf: ^3.11.1
  printing: ^5.13.2

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0

  # Utils
  uuid: ^4.5.1
  crypto: ^3.0.6
  intl: ^0.20.2
  share_plus: ^13.1.0
  wakelock_plus: ^1.2.10
  shared_preferences: ^2.3.4
  flutter_dotenv: ^6.0.1
  path_provider: ^2.1.5
  package_info_plus: ^10.2.0
  graphview: ^1.5.1
  dio: ^5.4.0
  flutter_secure_storage: ^10.3.1
  google_sign_in: ^6.2.1
  google_sign_in_platform_interface: ^2.5.0

  sign_in_with_apple: ^7.0.1
  image_picker: ^1.1.2
  socket_io_client: ^3.1.6
  url_launcher: ^6.3.2
  fl_chart: ^0.69.2
  phosphor_flutter: ^2.1.0
  shadcn_ui: ^0.53.6

  # Firebase & Push Notifications
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/logos/
