// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bgmYm1rBk_bBhmE_OMfh033kRHa-z9U',
    appId: '1:1021790177840:web:0a8f7954b9ae1102adfbf5',
    messagingSenderId: '1021790177840',
    projectId: 'quanlygiaidau',
    authDomain: 'quanlygiaidau.firebaseapp.com',
    storageBucket: 'quanlygiaidau.firebasestorage.app',
    measurementId: 'G-8PMJ08ME3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx-KMpk6mQejfr5kAIX22nqv9ZlY_ERrM',
    appId: '1:1021790177840:android:ec5c43863ab5da85adfbf5',
    messagingSenderId: '1021790177840',
    projectId: 'quanlygiaidau',
    storageBucket: 'quanlygiaidau.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCroiMXqJqoVfDB8Fns7RqJH-piokNCF3M',
    appId: '1:1021790177840:ios:c7dcadd9e4d76898adfbf5',
    messagingSenderId: '1021790177840',
    projectId: 'quanlygiaidau',
    storageBucket: 'quanlygiaidau.firebasestorage.app',
    iosBundleId: 'com.example.appQuanlyGiaidau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCroiMXqJqoVfDB8Fns7RqJH-piokNCF3M',
    appId: '1:1021790177840:ios:c7dcadd9e4d76898adfbf5',
    messagingSenderId: '1021790177840',
    projectId: 'quanlygiaidau',
    storageBucket: 'quanlygiaidau.firebasestorage.app',
    iosBundleId: 'com.example.appQuanlyGiaidau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_bgmYm1rBk_bBhmE_OMfh033kRHa-z9U',
    appId: '1:1021790177840:web:0598cafa5ef45ea7adfbf5',
    messagingSenderId: '1021790177840',
    projectId: 'quanlygiaidau',
    authDomain: 'quanlygiaidau.firebaseapp.com',
    storageBucket: 'quanlygiaidau.firebasestorage.app',
    measurementId: 'G-1Y9KP65D55',
  );
}
